version: "3.8"

services:
  moon:
    container_name: moon_app
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    volumes:
      - ./:/app
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
    command: [ "air", "-c", "dev/.air.conf" ]
    healthcheck:
      test: curl --fail -s http://localhost:4010/api/ping || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - 4010:8000
    depends_on:
      - postgres
  postgres:
    container_name: moon_postgres
    image: postgres:10.12-alpine
    environment:
      POSTGRES_DB: moon-db
      POSTGRES_PASSWORD: moon
      POSTGRES_USER: moon
      PGDATA: /var/lib/postgresql/data/moon
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - 4011:5432
    restart: unless-stopped
volumes:
  gomod:
  gocache:
  db:
networks:
  default:
    name: moonlay-net
    ipam:
      driver: default
      config:
      - subnet:  172.27.0.0/16